GET http://localhost:4000/users
###
POST http://localhost:4000/users/signup
Content-Type: application/json

{
    "username": "Aanandan",
    "password": "password"
}
###
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "username": "Aanandan",
    "password": "password"
}